### ISSUE TITLE
Wrong `shellman` link

### ISSUE THREAD

**Issue by joaopalmeiro** [pawamoy/pawamoy#1]
Hi! 👋 

I was checking your shell-related projects from your GitHub profile and noticed that the link to `shellman` is wrong: https://github.com/pawamoy/pawamoy/blob/8c437ecd61a0f62ea94b8d4aa1bf7588fa211e0f/README.md#L38

If I'm correct, the link should be https://github.com/pawamoy/shellman.

**Comment by pawamoy** [comment]
Hey, thanks! Damn, somebody already reported broken links there and I thought I had fixed them all :joy:

**Comment by pawamoy** [comment]
OK, this is fixed! Thanks again @joaopalmeiro :relaxed:
